server:
  port: 9009


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client id here
            client-secret: client secret here
          facebook:
            client-id: client id here
            client-secret: client secret here