spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client id here
            client-secret: client secret here
          facebook:
            client-id: client id here
            client-secret: client secret here
  jpa:
    database: POSTGRESQL
    #    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        #        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        javax:
          cache:
            missing_cache_strategy: create
            use_second_level_cache: true
            use_query_cache: true
            region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/multiple
    username: postgres
    password: vlad

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace