spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        javax:
          cache:
            missing_cache_strategy: create
            use_second_level_cache: true
            use_query_cache: true
            region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:{port}/{dbname}
    username:
    password:

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace